version: 2

jobs:
  build:
    docker:
      - image: node:alpine
    working_directory: /forcelog
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --update openssl
            yarn install --silent
      - run:
          name: Authenticate with Salesforce
          command: |
            mkdir .sfdx
            echo $SFDC_KEY | base64 -d > .sfdx/deploy.key
            yarn run auth
      - run:
          name: Create deployment package
          command: yarn run convert
      - run:
          name: Deploy and run tests
          command: yarn run deploy

  static-analysis:
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - pmd-v6.0.1
      - run:
          name: Install PMD
          command: |
              if [ ! -d pmd-bin-6.0.1 ]; then
                  curl -L "https://github.com/pmd/pmd/releases/download/pmd_releases/6.0.1/pmd-bin-6.0.1.zip" -o pmd-bin-6.0.1.zip
                  unzip pmd-bin-6.0.1.zip
                  rm pmd-bin-6.0.1.zip
              fi
      - save_cache:
          key: pmd-v6.0.1
          paths:
              - pmd-bin-6.0.1
      - run:
          name: Run static analysis
          command: pmd-bin-6.0.1/bin/run.sh pmd -d . -R pmd.xml -f text -l apex

workflows:
  version: 2
  validate:
    jobs:
      - build
      - static-analysis
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build