version: 2

jobs:
  build:
    docker:
      - image: node:alpine
    working_directory: /forcelog
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --update openssl
            yarn install --silent
      - run:
          name: Authenticate with Salesforce
          command: |
            mkdir .sfdx
            echo $SFDC_KEY | .sfdx/deploy.key
            yarn run auth
      - run:
          name: Create deployment package
          command: yarn run convert
      - run:
          name: Deploy and run tests
          command: yarn run deploy